name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
  ARB_RPC_URL: ${{secrets.ARB_RPC_URL}}
  BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}
  BASE_GOERLI_RPC_URL: ${{secrets.BASE_GOERLI_RPC_URL}}
  MOONRIVER_API_KEY: ${{secrets.MOONRIVER_API_KEY}}
  MOONBEAM_API_KEY: ${{secrets.MOONBEAM_API_KEY}}
  ETHERSCAN_API_KEY: ${{secrets.ETHERSCAN_API_KEY}}
  BASESCAN_API_KEY: ${{secrets.BASESCAN_API_KEY}}

jobs:
  build_scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Clean Contracts
        run: forge clean

      - name: Compile Contracts
        run: forge build
