name: Foundry base integration tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}
  ETHERSCAN_API_KEY: ${{secrets.ETHERSCAN_API_KEY}}
  BASESCAN_API_KEY: ${{secrets.BASESCAN_API_KEY}}

jobs:
  run-base-tests:
    name: base-integration-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Integration Tests Base Mainnet
        run: time forge test --match-contract LiveSystemBaseTest --fork-url base -vvv

