name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
  ARB_RPC_URL: ${{secrets.ARB_RPC_URL}}

jobs:
  build_scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Clean Contracts
        run: forge clean

      - name: Compile Contracts
        run: forge build

      - name: Unit Test Contracts
        run: forge test -vvv --match-contract UnitTest

      - name: Integration Test Contracts
        run: forge test --match-contract IntegrationTest --fork-url $ETH_RPC_URL

      - name: Arbitrum Integration Test Contracts
        run: forge test --match-contract ArbitrumTest --fork-url $ARB_RPC_URL

      - name: Unit Test Deploy and Configure Contracts
        run: forge test --match-contract LiveSystemTest --fork-url baseGoerli

      - name: Integration Test Hundred Finance Exploit Fails
        run: forge test --match-contract HundredFinanceExploitTest --fork-url baseGoerli -vvv

      - name: Integration Tests Base Mainnet
        run: forge test --match-contract LiveSystemBaseTest --fork-url base -vvv
